### ISSUE TITLE
[Version: ] Not able to disable malware plugin

### ISSUE THREAD

**Issue by SKInvenioLSI** [cap-js/attachments#108]
**Describe the bug**
We are able to use the object store plugin for storing attachments and were able to successfully implement it.
We do not want to use the malware plugin, so we added the code to disable the malware in package.json file with below attributes
"attachments": {
    "scan": true
}

**To Reproduce**
Steps to reproduce the issue is added in the attachment.
Please note- we are trying to run in hybrid mode and the malware profile still seems to be active for some reason.

**Expected behavior**
the malware service was supposed to be disabled after setting it to false in package.json file but still shows up as shown in the attachment steps screeshot pdf

[ ] is it a regression issue? 
No

**Screenshots**
Screenshots have been added.
[Steps for Attachment.pdf](https://github.com/user-attachments/files/17461704/Steps.for.Attachment.pdf)

Kindly advise.

**Customer Info**
Saritha K
InvenioLSI

**Comment by muskansethi1** [comment]
Hi @SKInvenioLSI,
To disable scanning in hybrid mode, `"attachments": { "scan": false }` has to be set in `"cds" : { "requires" : { }}` in package.json. 
Please let me know if this works!

Best Regards,
Muskan

**Comment by SKInvenioLSI** [comment]
Hi Muskan,

Thank you for the prompt update.
The app now opens up but errors out while viewing the stored attachments post addition.

Kindly view the details shared in updated attachment.
[Steps to reprroduce attachment error in view pot changes.docx](https://github.com/user-attachments/files/17473537/Steps.to.reprroduce.attachment.error.in.view.pot.changes.docx)
Kindly advise.
Regards,
Saritha

**Comment by SKInvenioLSI** [comment]
Hi Muskan,

Hope you understand the subsequent issue that's being faced now from the plugin code. Please do let us know if we need to provide any more information around it or not.
Thanks & Regards,
Saritha

**Comment by muskansethi1** [comment]
Hi @SKInvenioLSI,

We have identified the issue and are working on it.

Best Regards,
Muskan Sethi

**Comment by SKInvenioLSI** [comment]
Hello Muskan,
please treat this message as a gentle reminder for checking on the bug that was identified couple of weeks back.
request you to please share an update if possible.
Regards,
Saritha

**Comment by SKInvenioLSI** [comment]
Hi Muskan,
This seems to be fixed now. Thank you for all the help provided.
Regards,
Saritha
