### ISSUE TITLE
[CONTRIBUTE] Kind DMS - SAP Document Management Serivce 

### ISSUE THREAD

**Issue by binpath** [cap-js/attachments#45]
Hi SAP,

i will like to contribute with the attachments for the service DMS in SAP BTP. I just forked and I want some help starting to develop this contribution. 

The specific reason or objective is because SAP Build Apps uses the upload only in DMS and not in object store. Because, the instances sometimes needs actions that calls an action to a CAP service and is necessary to put the DMS data to the entity so the CAP App know's where is the uploaded  file is in DMS. I hope i'm not wrong. 

regards, 
Cesar Felce

**Comment by RamIndia** [comment]
Hello Cesar!

Its already in development, Currently the internal team is working on it, Will check with them and get back to you.

Thanks,
Ram

**Comment by RamIndia** [comment]
Hello Cesar,

SDM plugin is now available, you can check it here: https://cap.cloud.sap/docs/plugins/#@cap-js/sdm !

Thanks,
Ram
