### ISSUE TITLE
Attchment plugin not working

### ISSUE THREAD

**Issue by developedbysom** [cap-js/attachments#47]
Hello,

Thanks for this repository first of all. It worked for me till 27th April 2024. I found there is a new version deployed after. No more the plug-in works!

`npm i @cap-js/attachments@*1.0.1`  doesn't install the previous version too. Kindly check once. 

Currently I see the below error appears while I try to link up to my existing CAP Project. I  confirm I haven't made any single change to my CAP project. 

![issue - plugin](https://github.com/cap-js/attachments/assets/70325382/b83aae11-2deb-4cb7-b471-87a4978ee632)

![issue - npm](https://github.com/cap-js/attachments/assets/70325382/d72a63e6-e58b-4db0-bb89-742a472bcd10)

- Thanks,  Somnath

**Comment by muskansethi1** [comment]
Hi @developedbysom,

What is the error being thrown by the plugin? Can you please share more details.

Best Regards,
Muskan

**Comment by RamIndia** [comment]
@developedbysom : Are you still facing this issue?

**Comment by developedbysom** [comment]
No, its resolved as it looks for a specific ui5 version. After fixing, it worked.
