### ISSUE TITLE
OData services stopped working after deployment of plugin

### ISSUE THREAD

**Issue by naveenvishal** [cap-js/attachments#50]
Hi Team,

I have used the plugin in my model.cds but the project goes into hang state and shows no error in terminal as shown in image. 

![image](https://github.com/cap-js/attachments/assets/40799785/2694506b-02b6-4519-8c0d-00f04bffdbe7)

![image](https://github.com/cap-js/attachments/assets/40799785/ccae50b6-cdec-4d3f-81ad-691230f9566a)

Even as an extend model, its shows the same result as hanged.

![image](https://github.com/cap-js/attachments/assets/40799785/3de434be-fd9c-48a7-acf8-00388d9e22e0)

Please suggest.

**Comment by muskansethi1** [comment]
Hi @naveenvishal,

What is the version of ui5 been used? You can check this here in the index.html in the webapp : src="https://ui5.sap.com/**1.121.0**/resources/sap-ui-core.js"

**Comment by muskansethi1** [comment]
Hi @naveenvishal ,

Can you try changing to version 1.121.0 once and see if it works then?

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,
It shows correctly now, Thank you !! Can you please suggest how can I save the attachments to database (sqlite, HANA db).

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,

I am facing below error when I deployed app to HANA db and ran 'cds watch --profile hybrid'-

![image](https://github.com/cap-js/attachments/assets/40799785/966c1bbe-84dd-4d3f-989c-36f5125437ec)

**Comment by naveenvishal** [comment]
Issue resolved by help from [MioYasutake](https://community.sap.com/t5/user/viewprofilepage/user-id/789)

**Comment by naveenvishal** [comment]
Problem persist and issues are there in deploy.
I tried to include in package.json as "attachments": {
            "kind": "db"
        }              
but the issues are there deployed as shared in file above.
Additionally, if I include it as 'requires', it stops the SF odata execution.

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,

Please suggest do I need to modify xs-app.json or mta.yaml file with any changes for this plugin.
I have updated package.json to include the plugin and changes works fine in development.
But in production it is causing conflict with existing OData service.  

https://community.sap.com/t5/technology-q-a/odata-services-stopped-working-after-deployment-of-plugin/qaq-p/13705337

Please suggest if I need to additionally include the plugin details (mta.yaml, xs-app.json).

**Comment by muskansethi1** [comment]
Hi @naveenvishal,

I will have a look into this issue and get back to you.

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,

Please check the issue https://github.com/cap-js/attachments/issues/52 for a well detailed steps of analysis and execution for the replication of the issue. Thanks to [MioYasutake](https://github.com/miyasuta) for detailed analysis.

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,

Just to update that with attachments new build release, the issue is still not fixed for me. 

[MioYasutake](https://github.com/miyasuta) please check from your end.

**Comment by muskansethi1** [comment]
Hi @naveenvishal,
We are still looking into this issue, the fix hasn't been released yet

**Comment by naveenvishal** [comment]
Hi @muskansethi1 ,
With 'Fixes for deployment' I thought it is related to this issue, my bad.

**Comment by muskansethi1** [comment]
Hi @naveenvishal 

We have identified the issue and are currently discussing it with the concerned colleagues about the same.

Best Regards,
Muskan

**Comment by muskansethi1** [comment]
Hi @naveenvishal ,

We have found the fix for this issue and will release it in the next version soon.

Best Regards,
Muskan

**Comment by muskansethi1** [comment]
Hi @naveenvishal ,
The fix is released in `@cap-js/attachments@1.1.2`. Please let me know if there are any issues.

Best Regards,
Muskan
