### ISSUE TITLE
Event handler code ignored in Cloud Foundry environment

### ISSUE THREAD

**Issue by miyasuta** [cap-js/attachments#52]
This issue is related to the following one:
https://github.com/cap-js/attachments/issues/50

## Issue
After adding @cap-js/attachment plugin, event handler stopped working in Cloud Foundry environment.

## Project Setup
https://github.com/miyasuta/cap-attachment

- In a CAP project created simply via `cds add tiny-samples`, I've added the following event handler file.

```javascript
const cds = require('@sap/cds');

module.exports = class CatalogService extends cds.ApplicationService {
    async init () {
        this.after('READ', 'Books', each => {
            each.title = each.title + ' --added by event handler';
        })
        return super.init();
    }
}
```

- @cap-js/attachment plugin has been enabled as per the guidance, and it is working without an issue.
```
using { my.bookshop as my } from './data-model';
using { Attachments } from '@cap-js/attachments';

extend my.Books with { attachments: Composition of many Attachments }
```
- For deployment, I have added the following settings to the package.json file, as I don't have an entitlement for SAP Object Store in my trial account.
```json
    "cds": {
        "requires": {
            "[production]": {
                "db": "hana",
                "auth": "xsuaa"
            },
            "attachments": {
                "kind": "db"
            }             
        }
    }
```

## Result
The even handler is working fine in the local environment. I could see the output as below:
![image](https://github.com/cap-js/attachments/assets/39408125/d264e83a-5422-492f-9ef0-f6dfc15c90cc)

However, after this project was deployed to the Cloud Foundry, the event hander stopped working as if the source code itself has been removed. The following screenshot shows a response from the deployed app captured with Postman.
![image](https://github.com/cap-js/attachments/assets/39408125/4ecebe81-a5c7-4c53-9733-cd069bc14468)

Am I missing any settings, or for productive environment, only SAP Object Store is supported?

**Comment by naveenvishal** [comment]
Hi Dev Team,

Please take this on priority. The issue https://github.com/cap-js/attachments/issues/50 which I raised also sync with this issue, impacting our production build. Please prioritize.

Thanks and Best Regards,
Naveen Vishal

**Comment by muskansethi1** [comment]
Hi @miyasuta 

We have identified the issue and are currently discussing it with the concerned colleagues about the same.

Best Regards,
Muskan

**Comment by imran612** [comment]
Hello Team,
Our application got impacted due to this issue, event handlers are not invoked as a result odata calls to backend S4 is not happening. Any idea when this would be resolved?

**Comment by sachux** [comment]
Hi All,

I had a similar issue and adding @impl to the service.cds resolved the issue for me. 
May be this can be a workaround until the underlying issue is resolved.

```
@impl: 'srv/cat-service.js'
service CatalogService 
```

Thanks,
Sachin Srambickal

**Comment by muskansethi1** [comment]
Hi @miyasuta , @imran612 , @sachux ,

We have found the fix for this issue and will release it in the next version soon.

Best Regards,
Muskan

**Comment by muskansethi1** [comment]
Hello @miyasuta, @imran612, @sachux 

The fix is released in `@cap-js/attachments@1.1.2`. Please let me know if there are any issues.

Best Regards,
Muskan

**Comment by miyasuta** [comment]
Hi @muskansethi1,
Thanks for the update. I confirmed that the issue has been resolved.

**Comment by naveenvishal** [comment]
> Hi @muskansethi1, Thanks for the update. I confirmed that the issue has been resolved.

Thanks [miya](https://github.com/miyasuta) for your valuable help !
