### ISSUE TITLE
CAP/Fiori Elements application error during save

### ISSUE THREAD

**Issue by ch-sap** [cap-js/attachments#58]
Hi,

we have a CAP/Fiori Elements application with cap-js/attachment and deployed it to cloud foundry. We used object store to save the attachments.

The attachment association is added to an entity which is draft-enabled

The attachment reuse UI is shown and I could successfully upload a text file, but when I save the draft, I get an error.

**The CF log** shows me:
46f4e81c0e6","timestamp":1717600545660,"msg":"sql syntax error: incorrect syntax near \")\": line 1 col 100 (at pos 100)","message":"sql syntax error: incorrect syntax near \")\": line 1 col 100 (at pos 100)","code":257,"sqlState":"HY000","position":100,"query":"SELECT url AS \"url\" FROM localized_PoetrySlamService_PoetrySlams_attachments ALIAS_1 WHERE ID IN ( )"

**In chrome, I get:** Log-dbg.js:499 2024-06-05 17:15:45.205100 Failed to execute /PoetrySlams(ID=79ceab87-300d-4b66-8cc3-f82c679b77a1,IsActiveEntity=false)/PoetrySlamService.draftActivate(...) - Error: Communication error: 500 Internal Server Error

Could you please give advice?

Best regards,
Christine

**Comment by muskansethi1** [comment]
Hi @ch-sap,

Can you check which version of the plugin is being used?
This issue has been resolved in `version 1.1.1`

Best Regards,
Muskan

**Comment by ch-sap** [comment]
Hello Muskan,

issue is solved with the newest version. Thank you.

Best regards,
Christine
