### ISSUE TITLE
SAPUI5 Version conflicts (1.123 and 1.124)

### ISSUE THREAD

**Issue by Rediate15** [cap-js/attachments#72]
Hello there,

I've recently noticed that the cap-js/attachments plugin is incompatible with the SAPUI5 version 1.123 and 1.124 (1.125 works fine).
Specifically there seems to be an issue with missing ui5 functions, which leads to the app not loading:
![image](https://github.com/cap-js/attachments/assets/72558545/4a3e845d-8421-4b59-897b-1f621b538803)

Sometimes also an duplicate id error is thrown:
![image](https://github.com/cap-js/attachments/assets/72558545/35b95769-7364-48ae-8b63-1c7b4852b116)

Since I've only been able to find a reference that UI5 version 1.121.0 or higher (^1.121.0) is required, this version incompatibility should probably be documented somewhere.

Versions:
@cap-js/attachments: 1.0.2
@cap-js/cds-types: 0.2.0
@sap/cds: 7.9.2
@sap/cds-compiler: 4.9.4
@sap/cds-dk: 7.6.0
@sap/cds-dk (global): 7.9.3
@sap/cds-fiori: 1.2.3

Best regards
Timo

**Comment by muskansethi1** [comment]
Hi @Rediate15,

Yes, the Attachments table doesn't work with the UI5 versions 1.123 and 1.124, thank you for pointing this out. We will update the readme for the same.

Best Regards,
Muskan
