### ISSUE TITLE
Support for NodeJs version > 17

### ISSUE THREAD

**Issue by WAVIFICATION** [cap-js/attachments#79]
### Context:
SAP BTP Cloud Foundry environment recommends using Node.js versions 18 and 20 for deployment. You can find more information on their recommendations here: [SAP BTP CF Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/developing-node-js-in-cloud-foundry-environment).

### Issue:
When attempting to install the package with Node.js versions 18 or 20, the following warning is displayed:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@cap-js/attachments@1.1.3',
npm WARN EBADENGINE   required: { node: '^17.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
```

### Request:
To ensure compatibility and leverage the latest Node.js features and security updates, I kindly request that the @cap-js/attachments package be updated to support Node.js versions 18 and 20.

This update would be highly beneficial for developers deploying applications in environments that recommend or require these versions.

**Comment by muskansethi1** [comment]
Hi @WAVIFICATION,

We have updated the restriction of Node in the latest release.

Best Regards,
Muskan
