### ISSUE TITLE
Update @sap/cds version to 8

### ISSUE THREAD

**Issue by yashmeet29** [cap-js/attachments#86]
Hi colleagues,
cap-js/sdm team tried to update the @sap/cds version to 8, but we were getting error in build. Error was of version mismatch because cap-js/attachments repository uses cds v7, and attachments is added as a dependency in cap-js/sdm plugin.
Please refer this comment from @chgeo https://github.com/cap-js/sdm/pull/44#issuecomment-2202003089

All plugins needs to be on @sap/cds v8.

**Comment by muskansethi1** [comment]
Hi @yashmeet29 , We have cds support for >=7.6 version.

What is the error that is coming?

**Comment by yashmeet29** [comment]
Hi @muskansethi1, I updated `"@sap/cds": ">=8"` in @cap-js/sdm and then i am executing `npm i` by packaging `@cap-js/sdm` inside incidents-app. I am getting below error:

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @capire/incidents@1.0.0
npm error Found: @sap/cds@8.0.4
npm error node_modules/@sap/cds
npm error   @sap/cds@">=7" from the root project
npm error   peer @sap/cds@">=7.6" from @cap-js/attachments@1.1.4
npm error   node_modules/@cap-js/attachments
npm error     @cap-js/attachments@"latest" from @cap-js/sdm@1.0.2
npm error     node_modules/@cap-js/sdm
npm error   5 more (@cap-js/db-service, @cap-js/sdm, @cap-js/sqlite, ...)
npm error
npm error Could not resolve dependency:
npm error @cap-js/audit-logging@"^0.6.0" from the root project
npm error
npm error Conflicting peer dependency: @sap/cds@7.9.4
npm error node_modules/@sap/cds
npm error   peer @sap/cds@"^7" from @cap-js/audit-logging@0.6.0
npm error   node_modules/@cap-js/audit-logging
npm error     @cap-js/audit-logging@"^0.6.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

```
Looks like we need to update the cds version to 8 in incidents-app as well as in @cap-js/audit-logging

**Comment by muskansethi1** [comment]
Hi Yashmeet,

As discussed, cds 8 adaption in Attachments plugin has been released in version 1.1.6.
Can we close this issue then?

Best Regards,
Muskan

**Comment by yashmeet29** [comment]
Hi Muskan,
Thanks for the fix.
Let us verify this once with latest Attachments. And then we can close this.

Regards,
Yashmeet

**Comment by yashmeet29** [comment]
Hi @muskansethi1, thanks for the fix. It's working now.

Regards,
Yashmeet
