### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by DanSchlachter** [cap-js/attachments#92]
The screenshots in https://cap.cloud.sap/docs/plugins/#attachments and the git repo itself are outdated.
As the UI control doesn't have the icon anymore, it looks different now

**Comment by RamIndia** [comment]
@muskansethi1 : Is this done already?

**Comment by muskansethi1** [comment]
@RamIndia It is completed.
@DanSchlachter Thank you!
Closing this issue now.
