### ISSUE TITLE
[Version: ] Attachments with no name and not able to download it

### ISSUE THREAD

**Issue by agiguere** [cap-js/attachments#96]
**Describe the bug**

I created a sample CAP app in BAS with only 1 entity named Books
I added a composition relationship to the attachment entity

In my service, I have exposed the books entity and added
annotated Books with @odata.draft.enabled;

I am running the app with the hybrid profile from BAS
cds watch --profile hybrid

the attachments UI is there below my books table
however when I upload an attachment, the attachment name is not display and I can after that download it or open it
also if I tried to update the filed note, I got an error 
"Cannot read properties of undefined (reading 'endsWith')"

I am using Object Store with Amazon S3 bucket

thanks

**Screenshots**
<img width="1705" alt="Screenshot 2024-08-15 at 4 00 53 PM" src="https://github.com/user-attachments/assets/fba86776-0f24-4d9e-a3a2-0d468352d2f1">
<img width="1265" alt="Screenshot 2024-08-15 at 5 39 27 PM" src="https://github.com/user-attachments/assets/42c11076-5905-4deb-b916-153205224310">

**Comment by muskansethi1** [comment]
Hi @agiguere,

The fix is released in the latest version 1.1.6.

Best Regards,
Muskan Sethi
